platform :ios, '8.2'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
use_frameworks!

target 'assignment3' do
    pod 'BDBOAuth1Manager'
    #pod 'AFNetworking', '~> 2.5'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'KFSwiftImageLoader', '~> 2.0'
end

